# This section will create a secret in the Kubernetes cluster.
# We need this for private docker repos.
apiVersion: v1
kind: Secret
metadata:
  name: regcred
data:
  .dockerconfigjson: DOCKER_CONFIG
type: kubernetes.io/dockerconfigjson
---
# This section will create a deployment in the Kubernetes cluster
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vaxhub-deploy
  labels:
    app: vaxhub-app
spec:
  selector:
    matchLabels:
      app: vaxhub-app
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: vaxhub-app
    spec:
      containers:
      - name: vaxhub-app
        image: DOCKERHUB_USERNAME/DOCKERHUB_REPOSITORY:IMAGE_LABEL
        imagePullPolicy: Always
        ports:
        - containerPort: 3001
      imagePullSecrets:
      - name: regcred
---
# This section will create a service in the Kubernetes cluster
# so that the deployment can be accessed from the outside
apiVersion: v1
kind: Service
metadata:
  name: vaxhub-service
  labels:
    app: vaxhub-app
spec:
  type: LoadBalancer
  selector:
    app: vaxhub-app
  ports:
    - protocol: TCP
      name: http
      port: 80
      targetPort: 3001
