apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
data:
  prometheus.yml: |-
    global:
      scrape_interval: 15s
      evaluation_interval: 15s
    scrape_configs:
      - job_name: "nodejs-monitor"
        static_configs:
          - targets: ["vaxhub-service.default.svc.cluster.local:80"]
