name: Build and deploy Node.js app to linode
on:
  push:
    branches:
      - master
  workflow_dispatch:
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: login to dockerhub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Kubernetes set context
        uses: Azure/k8s-set-context@v3
        with:
          method: kubeconfig
          kubeconfig: ${{ secrets.KUBE_CONFIG }}
      - name: Set database secrets
        uses: azure/k8s-create-secret@v2
        with:
          namespace: 'vaxhub-app'
          secret-type: 'generic'
          secret-name: DB_USERNAME
          data: ${{ secrets.DB_USERNAME }}
      - uses: azure/k8s-create-secret@v2
        with:
          namespace: 'vaxhub-app'
          secret-type: 'generic'
          secret-name: DB_PASSWORD
          data: ${{ secrets.DB_PASSWORD }}
      - uses: azure/k8s-create-secret@v2
        with:
          namespace: 'vaxhub-app'
          secret-type: 'generic'
          secret-name: DB_PORT
          data: ${{ secrets.DB_PORT }}
      - uses: azure/k8s-create-secret@v2
        with:
          namespace: 'vaxhub-app'
          secret-type: 'generic'
          secret-name: DB_HOST
          data: ${{ secrets.DB_HOST }}
      - name: Docker Build and Push, Kubernetes apply
        run: |
          docker build --tag ${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.DOCKERHUB_REPOSITORY }}:${{ github.sha }} .
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.DOCKERHUB_REPOSITORY }}:${{ github.sha }}
          export DOCKER_CONFIG=$(cat ~/.docker/config.json | base64 -w 0)
          sed -i'' -e 's/DOCKERHUB_USERNAME/${{ secrets.DOCKERHUB_USERNAME }}/g' -e 's/DOCKERHUB_REPOSITORY/${{ secrets.DOCKERHUB_REPOSITORY }}/g' -e 's/IMAGE_LABEL/${{ github.sha }}/g' -e "s/DOCKER_CONFIG/$DOCKER_CONFIG/g" k8s.yaml
          kubectl apply -f k8s.yaml
